language: cpp
sudo: false
compiler:
  - gcc
  - clang
cache: apt
env:
  global:
    # Coverity Token
    - secure: "wnslCeFqgjcP1rNGtxawCYR/P9izUgyUHkCoXH6Noah7ONO4GyFRkoP3VpyP7TEHZ2O0vpf4uyKSl1COKkCMgYXGZ3En3+fCFlJGFqNMAKMbfHkC8trdbQzKiolPOURtnQuX0mG3SriXv5SOSGtP1x2+h1/S7COuR571YRbkqdGbJY9/Wsk6Eqf5Yh4dPCTaMHNAj5ag92zc6+N7DPraKJJSjSzBJbHhZAP5J165kBsl+BwOytR/+poLbbYNUYcBIXjl+fdifgZxDn4yaox3uyGkXmeY0BawSgzIA6vIMWUIN1eYxjfoaIVVTDSZUN98Y5rlhEx/X9gMgjdVmF67xr+p4cXLXUCNgWhs7b7UC0jSnd7zoKPmur2piUuaKvUzgwOIauombybV52tkBDtFf3WGC4I4OrWL8DZGwK2m/uLMFwmCdUwiugMMRCzVCwyyUGlwUo4iiBmwwN5uadiQdzrjWKnXSAgcwzVcgyuy3HP74R02etVh2V2fuZZs4MAm4rtRqqlE1IIFu7MKGmPkFIgsnrkvM5WuC37sTsYdJ7l23Q17KkQQAdQv1rTgeNyTaTIH8NqxUdwRyzf74kf1QcCvpzjBXjr+O+bcDxArGWnKw3C2NmuD4pnQmg9oRzVFEWGEpxO5M8OCBVTFv2m+KwFX+YzU8aOzgwuo5RW87cU="
before_install:
  - chmod +x premake5
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
before_script:
  - ./premake5 gmake 
script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make config=releasedll -j4; fi
branches:
  only:
  - master
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
  coverity_scan:
    project:
      name: "Xleek/Muon"
      description: "Build submitted via Travis CI"
    build_command_prepend: "./premake5 gmake"
    build_command:   "make config=releasedll -j4"
    branch_pattern: coverity_scan