language: cpp
sudo: false
compiler:
  - gcc
  - clang
cache: apt

branches:
  only:
    - master
    - coverity_scan

env:
  global:
   # COVERITY_SCAN_TOKEN
   - secure: "r1qjlTKCfNnQRDtcWGy1O3Y4RkaMna8J9o7qDPz5pOgwe+8FKqvdF/CYJCVt+g4nN0jsTI/ZG+6q18IEkmM1ntt6h4qqu89z4c2K5eII2+TRJMB9yyidGQ7pPR2drKHyExP3YBex10N5vR/GOyNJj01Qan/mAhHNyAigeBa1lbNSdZU8nkK7xiyjOp4znTOR7u/3dNWsQ0RiwAvFbOR93lvD0OTS27B1rE2tYlhY6stJZbbIqei/C/dGl3iOoHv8fgmqeTjHrUOe8KAce5KEsp6+FAzubOnLuBtHWKxKp+Nt2KJTkMN3byATuQ1XBQBY4Js8FWSy21HIUM+HEeYJvvhFGE3WXC0dmFmPYt3SMvmJVyQZH1tTuR1f0/VnbPKr+gfpbCJNR/KZQ/GTQYbW59X9m1sL86tsJjjBmjPZLZ6mi01KaCUqOGYBksaBU+LChg64VD2ZvroajrClQel0k1w8/Ruz+xhXtqvVifI7eLEcVJp5ylK5u2wpiL+q6GiJ8CwfRXyrm26mbCFj2KmOVnjthMQpiawoMVDcP6hQevLj7L1gp6sI87gf7A9D8NTpSgduMJC5grQ8+eW9hCIpSii0XhojNOyO2UfwgclieVZFuTmNgkkEy2ogyPutIVNi0U6ZsJEFSuDPa3PEJqLxgWxlIDFKT8u7UjDrafzRVhw="

  matrix:
    - BUILD_CONFIG=finaldll
    - BUILD_CONFIG=finallib

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - sh travis_setup.sh

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make config=${BUILD_CONFIG} ; fi

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

  coverity_scan:
    project:
      name: "Xipiryon/Haize"
      description: "Build submitted via Travis CI"
    notification_email: louis.schnellbach@gmail.com
    build_command_prepend: "sh travis_setup.sh"
    build_command:   "make config=finaldll"
    branch_pattern: coverity_scan
