language: cpp
sudo: false
compiler:
  - gcc
  - clang
env:
  - BUILD_CONFIG=debugdll
  - BUILD_CONFIG=releasedll
  - BUILD_CONFIG=debuglib
  - BUILD_CONFIG=releaselib
cache: apt
before_install:
  - chmod +x premake5
before_script:
  - ./premake5 gmake 
script:
  - make config=${BUILD_CONFIG}
branches:
  only:
  - master
os:
  - linux
  - osx
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8