language: cpp
compiler:
  - gcc
  - clang
env:
  - OPTIM_LEVEL=debug
  - OPTIM_LEVEL=release
  - LIB_LINK=dll
  - LIB_LINK=lib
cache: apt
before_install:
  - sudo apt-get update -qq
before_script:
  - ./premake gmake 
script:
  - make config=${OPTIM_LEVEL}${LIB_LINK}
branches:
  only:
  - master
os:
  - linux
  - osx
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8